### PR TITLE
only show focus ripple from keyboard

### PR DESCRIPTION
**Pull request by notwaldorf**

### CODE REVIEW

**Comment by cdata** [comment]
LGTM :+1: Do the tests pass locally for you?

**Comment by notwaldorf** [comment]
No, but not because of this PR. Soooomeone changed the elevation from 3 to 2 and didn't run the tests 😛. Fixing

**Comment by notwaldorf** [comment]
I added a fixed for the `set disabled` test. Unfortunately, the same fix needs to be done in `paper-button` (you can see in the demo that if you do a `document.querySelectorAll('paper-button')[0].disabled = true`, the button becomes disabled but the elevation doesn't get updated.

**Comment by cdata** [comment]
I take back the LGTM - please do not merge this PR.

**Comment by notwaldorf** [comment]
Closing this CL as @cdata fixed it somewhere else.

**Pull request closed without merging**
