### PR TITLE
Update demos to Polymer 1.1

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by notwaldorf** [comment]
This looks great, but you need to bump the Polymer dependency to `1.1.0`

**Comment by abdonrd** [comment]
@notwaldorf the actual Polymer dependency version is ^1.2.1. :)

**Comment by notwaldorf** [comment]
Awesome! Thanks! 🍁

**Comment by abdonrd** [comment]
:gem:

**Pull request merged**
